package CalculatorRoundbutton;

/**
 *
 * @author Tamim
 */
public class CalculatorRoundbuttons extends javax.swing.JFrame {
    double firstnum;
    double secondnum;
    double result;
    String operations;
    
 
    public CalculatorRoundbuttons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnDisplay = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jBtnEquals = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jBtnClear = new javax.swing.JButton();
        jBtnBackSpace = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnSub = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtnPM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jBtnDisplay.setText(" ");
        jBtnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 7, 312, 60));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("jTextField1");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 312, 47));

        jBtnEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEquals.setText("=");
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 70, 61));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 312, 47));

        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 61));

        jBtnBackSpace.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnBackSpace.setText("Del");
        jBtnBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBackSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 61));

        jBtnDiv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 70, 61));

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 61));

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 70, 61));

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 70, 61));

        jBtnSub.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnSub.setText("-");
        jBtnSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 70, 61));

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 70, 61));

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 70, 61));

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 70, 61));

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 70, 61));

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 70, 61));

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 70, 61));

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 70, 61));

        jBtnMul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnMul.setText("*");
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 70, 61));

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 70, 61));

        jBtnDot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnDot.setText(".");
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 70, 61));

        jBtnPM.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBtnPM.setText("+/-");
        jBtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 70, 61));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualsActionPerformed
        String answer;
        secondnum =  Double.parseDouble(jtxtDisplay.getText());
     if (operations == "+")
        {
            result = firstnum + secondnum;
            answer = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
     
     else if (operations == "-")
        {
         result = firstnum - secondnum;
         answer = String.format("%.2f", result);
         jtxtDisplay.setText(answer);
        }
    else if (operations == "*") 
        {
         result = firstnum * secondnum;
         answer = String.format("%.2f", result);
         jtxtDisplay.setText(answer);
        }   
     else if (operations == "/" )
        {
         result = firstnum / secondnum;
         answer = String.format("%.2f", result);
         jtxtDisplay.setText(answer);
        }    
    
    }//GEN-LAST:event_jBtnEqualsActionPerformed

    private void jBtnSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubActionPerformed
        
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.getText();
        operations ="-";    
    }//GEN-LAST:event_jBtnSubActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn4.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn4.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
         String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn5.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn5.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
              String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn6.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn6.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
     
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.getText();
        operations ="+"; 
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn1.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn1.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String EnterNumber = "";
      
          EnterNumber = jBtnDisplay.getText() + jBtn2.getText();
            jBtnDisplay.setText(EnterNumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
      String EnterNumber = "";
      
          EnterNumber = jBtnDisplay.getText() + jBtn3.getText();
            jBtnDisplay.setText(EnterNumber);
       
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.getText();
        operations ="*"; 
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
              String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn0.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn0.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
     
        if (! jtxtDisplay.getText().contains("."))
        {
         jtxtDisplay.setText(jtxtDisplay.getText() + jBtnDot.getText());  
        }
    }//GEN-LAST:event_jBtnDotActionPerformed

    private void jBtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPMActionPerformed
     
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops =ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnPMActionPerformed

    private void jBtnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDisplayActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
         
        String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn7.getText());
        }    
        else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn7.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
          String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn8.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn8.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
         String EnterNumber = jtxtDisplay.getText(); 
        if (EnterNumber =="")
        {
            jtxtDisplay.setText(jBtn9.getText());
        }    
       else 
        {
            EnterNumber = jtxtDisplay.getText() + jBtn9.getText();
            jtxtDisplay.getText(EnterNumber);
        }
       
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
       
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackSpaceActionPerformed
    
        String backspace = null;
        
        if (jtxtDisplay.getText().length() > 0){
            StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
            strB.deleteCharAt(jtxtDisplay.getText().length() - 1);
            backspace = strB.toString();
            jtxtDisplay.setText(backspace);
        }
    }//GEN-LAST:event_jBtnBackSpaceActionPerformed

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.getText();
        operations ="/"; 
    }//GEN-LAST:event_jBtnDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorRoundbuttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorRoundbuttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorRoundbuttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorRoundbuttons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorRoundbuttons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBackSpace;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JTextField jBtnDisplay;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnPM;
    private javax.swing.JButton jBtnSub;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
  
